### ISSUE TITLE
The texts on Learn More page are too long and not shown correctly in low-resolution (720P)

### ISSUE THREAD

**Issue by boltomli** [TheBigBookofLatin/thebigbookoflatin.github.io#1]
What I see is cut off
![default](https://cloud.githubusercontent.com/assets/5236916/5939080/a2066b3c-a73b-11e4-96e3-b8d24991804d.PNG)

**Comment by VirusKA** [comment]
Well, that's embarrassing. Will fix immediately.

**Comment by VirusKA** [comment]
fixed

**Comment by boltomli** [comment]
Indeed, it's fixed. The new layout looks OK. Thanks!
